[env]
NODE_ENV = "development"

[settings]
experimental = true
go_default_packages_file = "~/.go"
idiomatic_version_file_enable_tools = ["npm"]
lockfile = true
minimum_release_age = "3d"
minimum_release_age_excludes = ["herdr"]

[settings.npm]
bun = false
package_manager = "aube"
