return {
  { import = 'plugins.config.actions_preview' },
  { import = 'plugins.config.dial' },
  { import = 'plugins.config.codediff' },
  { import = 'plugins.config.flash' },
  { import = 'plugins.config.gitsigns' },
  { import = 'plugins.config.grug_far' },
  { import = 'plugins.config.hover' },
  { import = 'plugins.config.inc_rename' },
  { import = 'plugins.config.mini_move' },
  { import = 'plugins.config.multicursor' },
  { import = 'plugins.config.neogit' },
  { import = 'plugins.config.origami' },
  { import = 'plugins.config.outline' },
  { import = 'plugins.config.package_info' },
  { import = 'plugins.config.patterns' },
  { import = 'plugins.config.refactoring' },
  { import = 'plugins.config.snacks' },
  { import = 'plugins.config.snacks_explorer' },
  { import = 'plugins.config.snacks_picker' },
  { import = 'plugins.config.symbol_usage' },
  { import = 'plugins.config.todo_comments' },
  { import = 'plugins.config.trouble' },
  { import = 'plugins.config.vim_tmux_navigator' },
  { import = 'plugins.config.which_key' },
}
