return {
  { import = 'plugins.config.conform' },
  { import = 'plugins.config.dap' },
  { import = 'plugins.config.dap_dart' },
  { import = 'plugins.config.dap_js' },
  { import = 'plugins.config.dap_nlua' },
  { import = 'plugins.config.freemarker' },
  { import = 'plugins.config.garbage_day' },
  { import = 'plugins.config.mason' },
  { import = 'plugins.config.mason_tool_installer' },
  { import = 'plugins.config.markdown_table_mode' },
  { import = 'plugins.config.mini_sessions' },
  { import = 'plugins.config.mini_test' },
  { import = 'plugins.config.neotest' },
  { import = 'plugins.config.nvim_lint' },
  { import = 'plugins.config.obsidian' },
  { import = 'plugins.config.octo' },
  { import = 'plugins.config.render_markdown' },
  { import = 'plugins.config.schemastore' },
  { import = 'plugins.config.showkeys' },
  { import = 'plugins.config.tailwind_fold' },
  { import = 'plugins.config.treesitter' },
  { import = 'plugins.config.treesitter_textobjects' },
  { import = 'plugins.config.ts_autotag' },
  { import = 'plugins.config.ts_error_translator' },
  -- { import = 'plugins.config.vim_wakatime' },
}
