# Extra autostart processes
# exec-once = uwsm app -- my-service

exec-once = clipse -listen
exec-once = ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false
