# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Alt + Space
  # numlock_by_default = true
  mouse_refocus = false

  follow_mouse = 2

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

device {
  name = mx-mchncl-m-keyboard
  kb_layout = us
  kb_variant = intl
  kb_model = pc105
  kb_options = compose:ralt
}

device {
  name = at-translated-set-2-keyboard
  kb_layout = br
  kb_variant =
  kb_model = abnt2
  kb_options = compose:ralt
}

gestures {
  workspace_swipe = true
}

# Scroll faster in the terminal
windowrule = scrolltouchpad 1.5, class:Alacritty
