# cSpell:disable
config:
  fallback-icon: ""
  show-name: true

icons:
  apt: "󰚰"
  bash: ""
  bob: ""
  brew: ""
  btm: ""
  btop: ""
  cargo: "󱘗"
  cfdisk: ""
  dnf: ""
  docker: "󰡨"
  dpkg: "󰚰"
  fdisk: ""
  flatpack: "󰚰"
  gh: ""
  git: "󰊢"
  g: ""
  go: ""
  htop: ""
  java: ""
  kubectl: "󱃾"
  lazydocker: "󰡨"
  lazygit: "󰊢"
  lf: ""
  lfcd: ""
  lua: "󰢱"
  luarocks: "󰢱"
  lvim: ""
  mvn: ""
  nala: "󰚰"
  node: ""
  nvim: ""
  parted: ""
  python: "󰌠"
  ruby: "󰴭"
  rustc: "󱘗"
  rustup: "󱘗"
  sdk: ""
  tig: "󰊢"
  tmux: ""
  top: ""
  vim: ""
  zap: "⚡"
  zsh: ""
