#!/usr/bin/env bash

%hidden MODULE_NAME="dir_name"

set -ogq "@dir_name" " #(basename \"#{pane_current_path}\" | rg --passthru $USER -r \"home\")"
set -ogq "@git_status" "#(gitmux -cfg \"#{TMUX_ROOT}/gitmux.conf\" \"#{pane_current_path}\")"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󰉋 "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#99d1db"
set -ogq "@catppuccin_${MODULE_NAME}_text" "#{E:@dir_name}#{E:@git_status}"

source -F "#{TMUX_ROOT}/plugins/tmux/utils/status_module.conf"
