#!/usr/bin/env bash

%hidden MODULE_NAME="indicator"

set -ogq "@color" "#{?client_prefix,#99d1db,#{?pane_in_mode,#e5c890,#{?pane_synchronized,#e78284,#8caaee}}}"
set -ogq "@text" " #{?client_prefix,WAIT,#{?pane_in_mode,COPY,#{?pane_synchronized,SYNC,TMUX}}}"

set -ogq "@catppuccin_${MODULE_NAME}_icon" " "
set -ogq "@catppuccin_${MODULE_NAME}_color" "#{E:@color}"
set -ogq "@catppuccin_${MODULE_NAME}_text" "#{E:@text}"

source -F "#{TMUX_ROOT}/plugins/tmux/utils/status_module.conf"
