#!/usr/bin/env bash

%hidden MODULE_NAME="memory"

set -g "@ram_low_bg_color" "#a5d4a7"
set -g "@ram_medium_bg_color" "#faec94"
set -g "@ram_high_bg_color" "#d6a8a6"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󰘚 "
set -ogq "@catppuccin_${MODULE_NAME}_color" "#{l:#{ram_bg_color}}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " #{l:#{ram_percentage}}"

source -F "#{TMUX_ROOT}/plugins/tmux/utils/status_module.conf"
