[tools]
atuin = "latest"
aube = "latest"
bat = "latest"
bob = "latest"
bottom = "latest"
btop = "latest"
choose = "latest"
copilot = "latest"
curlie = "latest"
delta = "latest"
direnv = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
ffmpeg = "latest"
fx = "latest"
fzf = "latest"
gdu = "latest"
github-cli = "latest"
glow = "latest"
gojq = "latest"
gum = "latest"
harper-cli = "latest"
herdr = "latest"
hk = "latest"
httpie-go = "latest"
hunk = "latest"
imagemagick = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
lefthook = "latest"
opencode = "latest"
pkl = "latest"
resvg = "latest"
ripgrep = "latest"
rtk = "latest"
starship = "latest"
stylua = "latest"
taplo = "latest"
television = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"
"cargo:koji" = "latest"
"cargo:pik" = "latest"
"cargo:tailspin" = "latest"
"cargo:https://github.com/lhvy/pipes-rs" = "latest"
"go:github.com/compozy/compozy/cmd/compozy" = "latest"
"go:github.com/arl/gitmux" = "latest"
"go:github.com/janosmiko/lfk" = "latest"
"npm:@colbymchenry/codegraph" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:context-mode" = "latest"
