$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

bindeld = , Caps_Lock, CapsLock, exec, $osdclient --caps-lock
bindeld = , Num_Lock, NumLock, exec, $osdclient --num-lock
