#!/usr/bin/env zsh

# CUSTOMS
POWERLEVEL9K_CUSTOM_ICON=$'echo \uf31c '

# ICONS
POWERLEVEL9K_ANDROID_ICON=$'\uf531 '
POWERLEVEL9K_APPLE_ICON=$'\uf302 '
POWERLEVEL9K_AWS_EB_ICON=$'\ufbdf '
POWERLEVEL9K_AWS_ICON=$'\uf270 '
POWERLEVEL9K_BACKGROUND_JOBS_ICON=$'\uf423 '
POWERLEVEL9K_BATTERY_ICON=$'\uf240 '
POWERLEVEL9K_CARRIAGE_RETURN_ICON=$'\ufb0b '
POWERLEVEL9K_DISK_ICON=$'\uf0a0 '
POWERLEVEL9K_EXECUTION_TIME_ICON=$'\uf608 '
POWERLEVEL9K_FAIL_ICON=$'\uf057 '
POWERLEVEL9K_FOLDER_ICON=$'\uf07b '
POWERLEVEL9K_FREEBSD_ICON=$'\uf30c '
POWERLEVEL9K_GO_ICON=$'\ue627 '
POWERLEVEL9K_HOME_ICON=$'\uf015 '
POWERLEVEL9K_HOME_SUB_ICON=$'\uf07c '
POWERLEVEL9K_KUBERNETES_ICON=$'\ufd31 '
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=$'  '
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\ue0b0'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=$'\ue0b1'
POWERLEVEL9K_LINUX_ICON=$'\uf17c '
POWERLEVEL9K_LOAD_ICON=$'\ue266 '
POWERLEVEL9K_LOCK_ICON=$'\uf83d '
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=$'╭─'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=$'╰─ '
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=$'├─ '
POWERLEVEL9K_NETWORK_ICON=$'\ufa9e '
POWERLEVEL9K_NODE_ICON=$'\uf898 '
POWERLEVEL9K_OK_ICON=$'\uf058 '
POWERLEVEL9K_PUBLIC_IP_ICON=$'\ufa9e '
POWERLEVEL9K_PYTHON_ICON=$'\uf81f '
POWERLEVEL9K_RAM_ICON=$'\uf85a '
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\ue0b2'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=$'\ue0b3'
POWERLEVEL9K_ROOT_ICON=$'\uf292 '
POWERLEVEL9K_RUBY_ICON=$'\ue791 '
POWERLEVEL9K_RUST_ICON=$'\ue7a8 '
POWERLEVEL9K_SERVER_ICON=$'\uf473 '
POWERLEVEL9K_SSH_ICON=$'(ssh) '
POWERLEVEL9K_SUNOS_ICON=$'\ufa98 '
POWERLEVEL9K_SWAP_ICON=$'\uf85a '
POWERLEVEL9K_SWIFT_ICON=$'\ufbe3 '
POWERLEVEL9K_SYMFONY_ICON=$'\ue757 '
POWERLEVEL9K_TEST_ICON=$'\ufb67 '
POWERLEVEL9K_TODO_ICON=$'\uf046 '
POWERLEVEL9K_VCS_BOOKMARK_ICON=$'\ufd2c '
POWERLEVEL9K_VCS_BRANCH_ICON=$'\uf418 '
POWERLEVEL9K_VCS_COMMIT_ICON=$'\uf417 '
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=$'\uf171 '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uf408 '
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=$'\uf296 '
POWERLEVEL9K_VCS_GIT_ICON=$'\uf7a1 '
POWERLEVEL9K_VCS_HG_ICON=$'\uf595 '
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$'\uf0ab '
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$'\uf0aa '
POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=$'\uf47f '
POWERLEVEL9K_VCS_STAGED_ICON=$'\uf055 '
POWERLEVEL9K_VCS_STASH_ICON=$'\uf01c '
POWERLEVEL9K_VCS_SVN_ICON=$'\uf65e '
POWERLEVEL9K_VCS_TAG_ICON=$'\uf9fc '
POWERLEVEL9K_VCS_UNSTAGED_ICON=$'\uf06a '
POWERLEVEL9K_VCS_UNTRACKED_ICON=$'\uf059 '
POWERLEVEL9K_VPN_ICON=$'(vpn) '
POWERLEVEL9K_WINDOWS_ICON=$'\uf17a '

# COLORS
POWERLEVEL9K_CUSTOM_ICON_BACKGROUND=005
POWERLEVEL9K_CUSTOM_ICON_FOREGROUND=015
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=015
POWERLEVEL9K_DIR_HOME_FOREGROUND=015
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=015
POWERLEVEL9K_RAM_FOREGROUND=015
POWERLEVEL9K_RAM_BACKGROUND=008
POWERLEVEL9K_STATUS_FAIL_BACKGROUND=001
POWERLEVEL9K_STATUS_FAIL_FOREGROUND=015
POWERLEVEL9K_STATUS_OK_BACKGROUND=002
POWERLEVEL9K_STATUS_OK_FOREGROUND=015
POWERLEVEL9K_TIME_FOREGROUND=000
POWERLEVEL9K_TIME_BACKGROUND=015
POWERLEVEL9K_USER_DEFAULT_FOREGROUND=015
POWERLEVEL9K_USER_DEFAULT_BACKGROUND=008
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=015
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=002
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=000
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=003
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=015
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=001

# CONFIGS
POWERLEVEL9K_HIDE_BRANCH_ICON=false
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=''
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S \ue384}"
POWERLEVEL9K_VCS_HIDE_TAGS=false
POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=true

POWERLEVEL9K_RAM_ELEMENTS=(ram_free)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_icon user dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs ram)
