local M = {}

M.alerts = {
  attention = " ",
  Error = "󰅚 ",
  error = "󰅚 ",
  Hint = " ",
  hint = " ",
  Info = " ",
  info = " ",
  question = " ",
  Warn = " ",
  warn = " ",
}

M.dap = {
  breakpoint = " ",
  debug = " ",
  logpoint = ".>",
  stopped = " ",
}

M.ft = {
  octo = " ",
}

M.git = {
  added = " ",
  branch = " ",
  commit    = "󰜘 ",
  conflict = " ",
  deleted   = " ",
  ignored = " ",
  modified = " ",
  removed = " ",
  renamed = " ",
  staged = " ",
  unmerged  = " ",
  unstaged = " ",
  untracked = " ",
}

M.kinds = {
  Array = " ",
  Boolean = " ",
  Class = " ",
  Codeium = "󰘦 ",
  Color = " ",
  Control = " ",
  Collapsed = " ",
  Constant = " ",
  Constructor = " ",
  Copilot = " ",
  Enum = " ",
  EnumMember = " ",
  Event = " ",
  Field = " ",
  File = " ",
  Folder = " ",
  Function = " ",
  Interface = " ",
  Key = " ",
  Keyword = " ",
  Method = " ",
  Module = " ",
  Namespace = " ",
  Null = " ",
  Number = " ",
  Object = " ",
  Operator = " ",
  Package = " ",
  Property = " ",
  Reference = " ",
  Snippet = " ",
  String = " ",
  Struct = " ",
  TabNine = "󰏚 ",
  Text = " ",
  TypeParameter = " ",
  Unit = " ",
  Unknown = " ",
  Value = " ",
  Variable = " ",
}

M.misc = {
  atom = "󰹻 ",
  dots = "󰇘",
  duck = "󰇥 ",
  folder = "",
  folder_open = "",
  goto = "󰑮 ",
  lsp = "󰣖",
  mark = " ",
  project = " ",
  robot = "󱙺 ",
  scissor = " ",
  search = " ",
  stack = " ",
  select = "▶ ",
  task = " ",
  telescope = "  ",
}

return M

-- return {
--   ActiveLSP = "",
--   FileCode = "󰅩",
--   FileModified = "",
--   FileReadOnly = "",
--   FolderClosed = "󰉋",
--   FolderEmpty = "󱋣",
--   FolderOpen = "󰝰",
--   Git = "󰊢",
--   GitAdd = "",
--   GitBranch = "",
--   GitChange = "",
--   GitConflict = "",
--   GitDelete = "",
--   GitIgnored = "",
--   GitRenamed = "",
--   GitUntracked = "󰛄",
--   ScrollText = "󰈚",
--   Selected = "󰌕",
--   TabClose = "",
--   Time = "󱑌",
--   VimIcon = "󰹻",
-- }

-- MacroRecording = "",
-- ActiveTS = "󰐾",
-- BufferClose = "󰅖",
-- DefaultFile = "",
-- NeovimClose = "󰅙",
-- Diagnostic = "󰒡",
-- DiagnosticError = "",
-- DiagnosticHint = "󰌵",
-- DiagnosticInfo = "󰋼",
-- DiagnosticWarn = "",
-- Ellipsis = "…",
-- GitDelete = "",
-- GitIgnored = "◌",
-- GitStaged = "✓",
-- GitUnstaged = "✗",
-- LSPLoaded = "",
-- LSPLoading1 = "",
-- LSPLoading2 = "",
-- LSPLoading3 = "",

-- ActiveLSP = "",
-- ActiveTS = " ",
-- BufferClose = "",
-- DapBreakpoint = "",
-- DapBreakpointCondition = "",
-- DapBreakpointRejected = "",
-- DapLogPoint = "",
-- DapStopped = "",
-- DefaultFile = "",
-- Diagnostic = "",
-- DiagnosticError = "",
-- DiagnosticHint = "",
-- DiagnosticInfo = "",
-- DiagnosticWarn = "",
-- Ellipsis = "",
-- FileModified = "",
-- FileReadOnly = "",
-- FileReadOnly = "",
-- FoldClosed = "",
-- FoldOpened = "",
-- FolderClosed = "",
-- FolderEmpty = "",
-- FolderOpen = "",
-- Git = "",
-- GitAdd = "",
-- GitBranch = "",
-- GitChange = "",
-- GitConflict = "",
-- GitDelete = "",
-- GitStaged = "",
-- GitUnstaged = "",
-- GitUntracked = "",
-- LSPLoaded = "",
-- LSPLoading1 = "",
-- LSPLoading2 = "",
-- LSPLoading3 = "",
-- MacroRecording = "",
-- Paste = "",
-- Search = "",

---@type barbecue.Config.kinds
-- kinds = {
--   File = "",
--   Module = "",
--   Namespace = "",
--   Package = "",
--   Class = "",
--   Method = "",
--   Property = "",
--   Field = "",
--   Constructor = "",
--   Enum = "",
--   Interface = "",
--   Function = "",
--   Variable = "",
--   Constant = "",
--   String = "",
--   Number = "",
--   Boolean = "",
--   Array = "",
--   Object = "",
--   Key = "",
--   Null = "",
--   EnumMember = "",
--   Struct = "",
--   Event = "",
--   Operator = "",
--   TypeParameter = "",
-- },

---@type dropbar_configs_t.icons.kinds.symbols
-- {
--   Array = '󰅪 ',
--   Boolean = ' ',
--   BreakStatement = '󰙧 ',
--   Call = '󰃷 ',
--   CaseStatement = '󱃙 ',
--   Class = ' ',
--   Color = '󰏘 ',
--   Constant = '󰏿 ',
--   Constructor = ' ',
--   ContinueStatement = '→ ',
--   Copilot = ' ',
--   Declaration = '󰙠 ',
--   Delete = '󰩺 ',
--   DoStatement = '󰑖 ',
--   Enum = ' ',
--   EnumMember = ' ',
--   Event = ' ',
--   Field = ' ',
--   File = '󰈔 ',
--   Folder = '󰉋 ',
--   ForStatement = '󰑖 ',
--   Function = '󰊕 ',
--   H1Marker = '󰉫 ', -- Used by markdown treesitter parser
--   H2Marker = '󰉬 ',
--   H3Marker = '󰉭 ',
--   H4Marker = '󰉮 ',
--   H5Marker = '󰉯 ',
--   H6Marker = '󰉰 ',
--   Identifier = '󰀫 ',
--   IfStatement = '󰇉 ',
--   Interface = ' ',
--   Keyword = '󰌋 ',
--   List = '󰅪 ',
--   Log = '󰦪 ',
--   Lsp = ' ',
--   Macro = '󰁌 ',
--   MarkdownH1 = '󰉫 ', -- Used by builtin markdown source
--   MarkdownH2 = '󰉬 ',
--   MarkdownH3 = '󰉭 ',
--   MarkdownH4 = '󰉮 ',
--   MarkdownH5 = '󰉯 ',
--   MarkdownH6 = '󰉰 ',
--   Method = '󰆧 ',
--   Module = '󰏗 ',
--   Namespace = '󰅩 ',
--   Null = '󰢤 ',
--   Number = '󰎠 ',
--   Object = '󰅩 ',
--   Operator = '󰆕 ',
--   Package = '󰆦 ',
--   Pair = '󰅪 ',
--   Property = ' ',
--   Reference = '󰦾 ',
--   Regex = ' ',
--   Repeat = '󰑖 ',
--   Scope = '󰅩 ',
--   Snippet = '󰩫 ',
--   Specifier = '󰦪 ',
--   Statement = '󰅩 ',
--   String = '󰉾 ',
--   Struct = ' ',
--   SwitchStatement = '󰺟 ',
--   Terminal = ' ',
--   Text = ' ',
--   Type = ' ',
--   TypeParameter = '󰆩 ',
--   Unit = ' ',
--   Value = '󰎠 ',
--   Variable = '󰀫 ',
--   WhileStatement = '󰑖 ',
-- }

---@class snacks.picker.icons
  -- icons = {
  --   files = {
  --     enabled = true, -- show file icons
  --   },
  --   keymaps = {
  --     nowait = "󰓅 "
  --   },
  --   tree = {
  --     vertical = "│ ",
  --     middle   = "├╴",
  --     last     = "└╴",
  --   },
  --   undo = {
  --     saved   = " ",
  --   },
  --   ui = {
  --     live        = "󰐰 ",
  --     hidden      = "h",
  --     ignored     = "i",
  --     follow      = "f",
  --     selected    = "● ",
  --     unselected  = "○ ",
  --     -- selected = " ",
  --   },
  --   git = {
  --     enabled   = true, -- show git icons
  --     commit    = "󰜘 ", -- used by git log
  --     staged    = "●", -- staged changes. always overrides the type icons
  --     added     = "",
  --     deleted   = "",
  --     ignored   = " ",
  --     modified  = "○",
  --     renamed   = "",
  --     unmerged  = " ",
  --     untracked = "?",
  --   },
  --   diagnostics = {
  --     Error = " ",
  --     Warn  = " ",
  --     Hint  = " ",
  --     Info  = " ",
  --   },
  --   kinds = {
  --     Array         = " ",
  --     Boolean       = "󰨙 ",
  --     Class         = " ",
  --     Color         = " ",
  --     Control       = " ",
  --     Collapsed     = " ",
  --     Constant      = "󰏿 ",
  --     Constructor   = " ",
  --     Copilot       = " ",
  --     Enum          = " ",
  --     EnumMember    = " ",
  --     Event         = " ",
  --     Field         = " ",
  --     File          = " ",
  --     Folder        = " ",
  --     Function      = "󰊕 ",
  --     Interface     = " ",
  --     Key           = " ",
  --     Keyword       = " ",
  --     Method        = "󰊕 ",
  --     Module        = " ",
  --     Namespace     = "󰦮 ",
  --     Null          = " ",
  --     Number        = "󰎠 ",
  --     Object        = " ",
  --     Operator      = " ",
  --     Package       = " ",
  --     Property      = " ",
  --     Reference     = " ",
  --     Snippet       = "󱄽 ",
  --     String        = " ",
  --     Struct        = "󰆼 ",
  --     Text          = " ",
  --     TypeParameter = " ",
  --     Unit          = " ",
  --     Unknown        = " ",
  --     Value         = " ",
  --     Variable      = "󰀫 ",
  --   },
  -- }
