#!/bin/bash

function show-colors() {
  for i in {0..15}; do
    print -Pn "%K{$i}   %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%8)):#7}:+$'\n'};
  done

  for i in {16..255}; do
    print -Pn "%K{$i}   %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'};
  done
}
